### ISSUE TITLE
Can't Install on Mac (10.11.4) running Rakudo Star 2016.04

### ISSUE THREAD

**Issue by tsalada** [retupmoca/P6-Digest-HMAC#4]
Digest::HMAC can't be installed using 
sudo panda --prefix=/Applications/Rakudo/share/perl6/site/bin/ --force install Digest::HMAC
However, Digest itself is installed.
Any advice would be appreciated.

**Comment by retupmoca** [comment]
Are you getting any error messages when you attempt to install it?
